# configs/tts_config.yaml
tts_config:
  model_name: teste1
  num_mels: 80
  num_freq: 1025
  sample_rate: 22050
  text_cleaner: english_cleaners
  ...

dataset:
  train_path: /tts/train.csv
  validation_path: /tts/validation.csv
  test_path: /tts/test.csv

output_path: /tts/modelo_treinado/